#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/git-branches-resource-request.XXXXXX)

cat > $payload <&0

uri=$(jq -r '.source.uri // ""' < $payload)
version=$(jq -r '.version // ""' < $payload)
branches=$(jq -r '.version.branches // ""' < $payload)

mkdir -p $destination

cd $destination

git_branches_json=$(jq -n "{
  \"uri\": \"$uri\",
  \"branches\": $branches
}")

echo $git_branches_json > git-branches.json

echo $version >&3
